name: Create flows
on:
  workflow_dispatch:
    inputs:
      upload:
        description: Upload flows to RapidPro
        type: boolean
        required: false
        default: false
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node dependencies
        run: npm ci
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
        run: |
          python -m parenttext_pipeline.cli
          echo upload=${{ inputs.upload }}
      - name: Publish output folder
        uses: actions/upload-artifact@v2
        with:
          name: Output Files
          path: output
